/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 19abb1fea6cf1e52369d515694550a20)
interface __BaseEnv_Env {
	IMAGES: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		IMAGES: R2Bucket;
		DB: D1Database;
	}
	interface ProductionEnv {
		IMAGES: R2Bucket;
		DB: D1Database;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
