/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false`.
// Service binding RPC methods are typed via the shared, dependency-free
// interfaces in @game-worker/shared/rpc-types (see that file for why —
// short version: a plain interface here avoids pulling another app's whole
// dependency graph, and its ambient `Env`, into this program). Note: this
// import makes the file a module, so the `Env` augmentation below must go
// inside `declare global` to still merge into the ambient global scope.
import type {AccountsRpc, FriendsRpc} from "@game-worker/shared/rpc-types";

interface __BaseEnv_Env {
    IMAGES: R2Bucket;
    DB: D1Database;
    FLAGS: Flagship;
    ACCOUNTS: AccountsRpc;
    FRIENDS: FriendsRpc;
}

declare global {
    namespace Cloudflare {
        interface GlobalProps {
            mainModule: typeof import("./src/index");
        }

        interface Env extends __BaseEnv_Env {
        }
    }

    interface Env extends __BaseEnv_Env {
    }
}
