/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false`.
// The `ACCOUNTS` service binding's RPC methods are typed via the shared,
// dependency-free `AccountsRpc` interface (see
// @game-worker/shared/rpc-types for why this is a plain interface rather
// than `Service<typeof AccountsService>`). Note: this import makes the
// file a module, so the `Env` augmentation below must go inside
// `declare global` to still merge into the ambient global scope.
import type {AccountsRpc} from "@game-worker/shared/rpc-types";

interface __BaseEnv_Env {
    DB: D1Database;
    ACCOUNTS: AccountsRpc;
}

declare global {
    namespace Cloudflare {
        interface GlobalProps {
            mainModule: typeof import("./src/index");
        }

        interface Env extends __BaseEnv_Env {
        }
    }

    interface Env extends __BaseEnv_Env {
    }
}
