/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false`.
// Service binding RPC methods are typed via the shared, dependency-free
// interfaces in @game-worker/shared/rpc-types (see that file for why —
// short version: a plain interface here avoids pulling another app's whole
// dependency graph, and its ambient `Env`, into this program). Note: this
// import makes the file a module, so the `Env` augmentation below must go
// inside `declare global` to still merge into the ambient global scope.
import type {AccountsRpc, PuzzleRpc} from "@game-worker/shared/rpc-types";

interface __BaseEnv_Env {
	DB: D1Database;
	ACCOUNTS: AccountsRpc;
	PUZZLE: PuzzleRpc;
	USER_DO: DurableObjectNamespace<import("./src/index").UserDO>;
}
declare global {
	namespace Cloudflare {
		interface GlobalProps {
			mainModule: typeof import("./src/index");
			durableNamespaces: "UserDO";
		}
		interface Env extends __BaseEnv_Env {}
	}
	interface Env extends __BaseEnv_Env {}
}
