/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cb22d86e784be8f912ce7cd57f5a864a)
interface __BaseEnv_Env {
	DB: D1Database;
	FLAGS: Flagship;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		DB: D1Database;
		FLAGS: Flagship;
	}
	interface ProductionEnv {
		DB: D1Database;
		FLAGS: Flagship;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
