/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false`.
// Service binding RPC methods are typed via the shared, dependency-free
// interfaces in @game-worker/shared/rpc-types (see that file for why —
// short version: a plain interface here avoids pulling another app's whole
// dependency graph, and its ambient `Env`, into this program). Note: this
// import makes the file a module, so the `Env` augmentation below must go
// inside `declare global` to still merge into the ambient global scope.
import type {AccountsRpc, CatalogRpc, LeaderboardRpc} from "@game-worker/shared/rpc-types";

interface __BaseEnv_Env {
    IMAGES: R2Bucket;
    PUZZLE_QUEUE: Queue;
    FLAGS: Flagship;
    AI: Ai;
    IMAGES_PUBLIC_URL: "https://dev.images.ryanb.co.za" | "https://staging.images.ryanb.co.za" | "https://images.ryanb.co.za";
    ACCOUNTS: AccountsRpc;
    BROWSE: CatalogRpc;
    LEADERBOARD: LeaderboardRpc;
    PUZZLE_DO: DurableObjectNamespace<import("./src/index").PuzzleDO>;
}

declare global {
    namespace Cloudflare {
        interface GlobalProps {
            mainModule: typeof import("./src/index");
            durableNamespaces: "PuzzleDO";
        }

        interface Env extends __BaseEnv_Env {}
    }

    interface Env extends __BaseEnv_Env {}
}
